export const opt = [
    { id: 1, value: "waifu" },
    { id: 2, value: "neko" },
    { id: 3, value: "shinobu" },
    { id: 4, value: "megumin" },
    { id: 5, value: "bully" },
    { id: 6, value: "cuddle" },
    { id: 7, value: "cry" },
    { id: 8, value: "hug" },
    { id: 9, value: "awoo" },
    { id: 10, value: "kiss" },
    { id: 11, value: "lick" },
    { id: 12, value: "pat" },
    { id: 13, value: "smug" },
    { id: 14, value: "bonk" },
    { id: 15, value: "yeet" },
    { id: 16, value: "blush" },
    { id: 17, value: "smile" },
    { id: 18, value: "wave" },
    { id: 19, value: "highfive" },
    { id: 20, value: "handhold" },
    { id: 21, value: "nom" },
    { id: 22, value: "bite" },
    { id: 23, value: "glomp" },
    { id: 24, value: "slap" },
    { id: 25, value: "kill" },
    { id: 26, value: "kick" },
    { id: 27, value: "happy" },
    { id: 28, value: "wink" },
    { id: 29, value: "poke" },
    { id: 30, value: "dance" },
    { id: 31, value: "cringe" },
]

